### ISSUE TITLE
Would you consider to have a converter for Merox

### ISSUE THREAD

**Issue by biopzhang** [yeastrc/proxl-import-stavrox#1]
Stavrox data don't share the same format with Merox. The current converter does not work on Merox data.

**Comment by talpa25** [comment]
Hi developer,

since Stavrox is no longer maintained and MeroX is kept for further development i would agree with the opinion of the previous speaker to adapt proxl-import for MeroX.

Best,

Roman

**Comment by mriffle** [comment]
Hi Roman,

Definitely. I didn't realize StavroX was no longer maintained. I'll take a look what's involved for developing a converter for MeroX as soon as I can!

Mike

**Comment by talpa25** [comment]
Hi Mike,
thank you very much for your commitment! I'm looking forward to the MeroX converter. :)
Best,
Roman

**Comment by mriffle** [comment]
Following up on this very old github issue! I just released a MeroX 2 to Proxl XML converter here: https://github.com/yeastrc/proxl-import-merox
